repos:
- repo: local
  hooks:
  - id: test
    name: Unit Tests
    entry: python backend/src/manage.py
    args: [test, pages]
    pass_filenames: false
    language: system
    types: [file, python]

