# Generated by Django 2.2.8 on 2020-01-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do Usuario')),
                ('email', models.EmailField(max_length=250, verbose_name='Email do Usuario')),
                ('cpf', models.CharField(max_length=120, verbose_name='Cpf do Usuario')),
                ('matricula', models.CharField(max_length=120, verbose_name='Matricula do Usuario')),
                ('password', models.CharField(max_length=120, verbose_name='Password do Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
